name: si_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - scipy
  - joblib
  - tqdm
  - matplotlib
  - h5py
  - pandas
  - xarray
  - hdbscan
  - scikit-learn
  - networkx
  - pybind11
  - loky
  - numba
  - jupyter
  - pyqt=5
  - pyqtgraph
  - ipywidgets
  - ipympl
  - umap-learn
  - datashader
  - bokeh
  - holoviews
  - colorcet
  - scikit-image
  - pip:
    - ephyviewer
    - https://github.com/NeuralEnsemble/python-neo/archive/master.zip
    - probeinterface
    - MEArec
    - docker
    - https://github.com/SpikeInterface/spikeinterface/archive/main.zip
    - https://github.com/SpikeInterface/spikeinterface-gui/archive/main.zip
    - https://github.com/magland/sortingview/archive/main.zip
